<?php

    // Conditions d'utilisations
    $CGU = [
        ["Introduction", 'Les présentes conditions générales d\'utilisation (ci-après désignées les "CGU") ont pour objet l\'encadrement juridique des modalités de mise à disposition des services du site Color Bass, et leur utilisation par "l\'Utilisateur". Les CGU doivent être acceptées par tout Utilisateur souhaitant accéder au site. Elles constituent le contrat entre le site et l\'Utilisateur. L\'accès au site par l\'Utilisateur signifie son acceptation des CGU.'],
        ["Contenu", "Le site Color Bass a pour objet de fournir une information concernant la nature de la Color Bass. Les contenus (notamment textes, photographies, vidéos, fonctionnalités, etc.) sont fournis à titre informatif."],
        ["Propriété Intellectuelle", "Les contenus du site Color Bass (textes, photographies, vidéos, fonctionnalités, etc.) ne sont pas protégés par les droits de propriété intellectuelle. Cependant, il est possible que certains contenus externes partagés sur le site (par exemple, des liens vers des vidéos sur YouTube) soient soumis aux droits d'auteur de leurs propriétaires respectifs. Il est de la responsabilité de l'Utilisateur de s'informer sur les éventuels droits d'auteur applicables avant de diffuser ou de reproduire ces contenus externes."],
        ["Responsabilité", "Les informations diffusées sur le site Color Bass sont fournies en l'état. Le site ne pourra être tenu responsable de toute imprécision, inexactitude ou omission dans les informations diffusées sur le site."],
        ["Liens Hypertextes", "Le site Color Bass peut contenir des liens hypertextes vers d'autres sites présents sur le réseau Internet. Les liens vers ces autres ressources vous font quitter le site Color Bass. Il est possible de créer un lien vers la page de présentation de ce site sans autorisation expresse."],
        ["Évolution des CGU", "Les CGU peuvent être modifiées à tout moment et sans préavis par le site Color Bass. Il est de l'Utilisateur de se référer régulièrement à la dernière version des CGU en vigueur"],
        ["Durée des CGU", "La durée des CGU est indéterminée. Le contrat produit ses effets à l'égard de l'Utilisateur à compter de l'utilisation du service."],
        ["Droit Applicable et Juridiction Compétente", "Les CGU sont régies par et interprétées conformément aux lois Françaises. Tout litige en relation avec l'utilisation du site Color Bass est soumis aux tribunaux compétents de Haguenau."]
    ];